### PR TITLE
Original Map Loader Fixes #2

### LINKED ISSUE #2: Settlers folder must be configurable on local developer machine
Furthermore, the paths currently configured in the global properties should be removed or replaced with the settlers standard installation path.

### PR DESCRIPTION
**Pull request by tomsoftware**
- Fix: Maploader saves the wrong Map Type if original was loaded.
- change map-heigh scale to 0.3 (see issues #211)
- Add: Quest-Text to original MapLoader "getDescription()"
- Fix: disable Quest-Text output

### CODE REVIEW

**Comment by codingberlin** [comment]
You reduced the scale of the heights because you was not able to build a building in the remake where you are able to build it in the original game.
But not only the heights affect if you can build a building. The blocking tiles of the building and the algorithm in the remake which determines the possibility to flattern influences if you can build a building or not.

Comparing the River map loaded in the original game ...
original

... and loaded in the remake with factor 0.3 ...
remake

... and loaded in the remake with factor 0.56 (127f / 225f) ...
factor05

... I would say factor 0.3 is too flat.

Until now it was not possible to compare the behavior constructions between the two games on the same map which leads to the conclusion that the other factors (flattern algorithm, blocked tiles of buildings etc. cause that you can't build your building.

@andreas-eberle what is your optioning about that?
(by the way: It seems to me that the original game has more or darker shadow in the landscape)

**Comment by tomsoftware** [comment]
@codingberlin with the building-dot-preview you can better compare the ("gefühlte") high in the games (see issues #211 [factor 0.5] and https://github.com/jsettlers/settlers-remake/pull/230 [factor 0.3 and original])... but may you are right: the real factor is somewhere in between 0.3 and 0.4 but 0.3 is not bad ;-)

There are match other differences in the remake e.g.:
- shadow of the hills
- you can’t build on the left-front-side of a hill
- the territory claimed by a tower is too big in the remake
- no decoration elements
but this is not a loader problem and need to discuss later in a other issue :-)

**Comment by codingberlin** [comment]
@tomsoftware I talked with @andreas-eberle about the building-dot-preview. He confirmed that not only the heights influence if you can build a building in the remake and that we should adjust the other factors in order to get a 1:1 translation of the heights between the original maps and the remake.

Thus I adjusted with commit 928339d7618c565d41dc168c37e82c953465be24 the ```CONSTRUCTION_MARK_SCALE_FACTOR``` which influences when to build a building is allowed.
I tested this with an own map loaded in the original game and the remake.
The construction marks does not fit exactly but better now. (This is because of the other mentioned factors e.g. the blocking tiles of a building which could differ between the original and the remake, too)

Could you verify that the new ```CONSTRUCTION_MARK_SCALE_FACTOR``` lets you build the lumberjack at your testmap running the remake with ```ORIGINAL_TO_REMAKE_HEIGHT_FACTOR = 127f / 225f``` and tell me if the new ```CONSTRUCTION_MARK_SCALE_FACTOR``` is ok or if I need to adjust it a bit more?

Regarding this pull request, please revert the changes:
```
//- Heigh of original maps are 0..225 and of remake 0..127 -> x = 127f / 225f;
//-  but remake allows much higher mountains -> x = 0.3
private final static float ORIGINAL_TO_REMAKE_HEIGHT_FACTOR = 0.3f;
```
Then I can merge the fixes and features of this pull request. (Thx for implementing them :)

Thx in advanced.

**Comment by codingberlin** [comment]
Thx

**Pull request merged**
