### PR TITLE
First working Version: open original Siedler 3 Map

### PR DESCRIPTION
**Pull request by tomsoftware**
+ Important change: Add "IMapLoader" to switch "New" and "Original" Maps
+ Important change: rename "New" Maps with ".smap" and original with ".map"
- ToDo: loading Siedlers
- ToDo: loading Buildings
- ToDo: loading Teams
- ToDo: add more objects
- ToDo: add landscape
- Known Bug: only ONE Team is added to [MapResourceInfo] in OriginalMapFileContentReader

### CODE REVIEW

**Comment by tomsoftware** [comment]
map_load
map_in_game

**Comment by codingberlin** [comment]
@andreas-eberle What do you think about how we should distinguish between the different map formats?

In my optinion we have 3 posibillities:
1) rename the format -> .smap = remake maps, .zmap = compressed remake maps, .map = original maps
2) transform all remake maps into .zmap -> .zmap = compressed remake maps, .map = original maps
3) distinguish based on the dir -> .map = remake maps, .zmap = compressed remake maps, /[original settlers dir]/*.map = original maps

**Comment by andreas-eberle** [comment]
I think option 1) is the best one. There are some problems with the zmap format, as this is totally slow on Android. Therefore I think we will stick with the uncompressed format for that (on a real computer there is no issue with 20MB maps anyways).
But I think we could change the map extension to .smap or maybe .rmap (remake-map) ;)

**Comment by codingberlin** [comment]
I just checked it out and loaded the original map A640-4-River.map which is my favorite one to test the computerplayer in the future because this map has identical start positions so we can balance the different computer player difficulties.

What should I say? ... it worked!! (grass / water missing the ToDos mentioned above)
Very cool!!

I merge it now and do the following:
- rename *.smap to *.rmap (as discussed above)
- refactor some java stuff (remove _ and transform to camel case)

**Pull request merged**
