### PR TITLE
Improve image preload cache.

### PR DESCRIPTION
**Pull request by michaelzangl**
This improves the way image preloading uses the image cache.

It also reduces memory consumption of graphics while the game is running since textures can be re-loaded from disk on demand (this should not happen in normal gameplay but e.g. after suspending the android app)

### CODE REVIEW

**Comment by michaelzangl** [comment]
Github seems to be slow on catching up. This should contain 3 commits.

**Comment by andreas-eberle** [comment]
@michaelzangl: Do you want to update this branch so it can be merged, or wait until after the gradle merge?

**Comment by michaelzangl** [comment]
I'd like to wait until after the gradle branch is merged.

**Comment by andreas-eberle** [comment]
@michaelzangl: Can you update this branch?

**Pull request closed without merging**
