### PR TITLE
add/fix movables

### PR DESCRIPTION
**Pull request by justangel**
based data on file 10, work is ongoing

### CODE REVIEW

**Comment by andreas-eberle** [comment]
@justangel: Please have a look at #71. It could influence your work here.

**Comment by andreas-eberle** [comment]
@justangel: I added entries for the WINEGROWER and fixed a problem with the FARMER movable in the movables.txt file. My changes are in the current master now and should not conflict with your changes yet.

**Comment by justangel** [comment]
Now I look, thanks

**Comment by justangel** [comment]
@andreas-eberle thanks, all merged ok, continue to work

**Comment by justangel** [comment]
https://github.com/jsettlers/settlers-remake/pull/73 i created another request for new branch, if this request not needed, maybe cancel it?

**Comment by andreas-eberle** [comment]
Hi @justangel:

The take drop branch is not working yet. In fact, I just started to work on it. So just continue collecting and correcting the images like you did here based on the current master. After I finished my work, we will see how and what to merge.

**Comment by andreas-eberle** [comment]
@justangel: I now merged the branch with the new take/drop animation system into the master. Furthermore it is now possible to specify negative durations (see winegrower's and farmer's RAISE_UP / BEND_DOWN sequences).

I'm afraid, you will have some merging to do, as I had to update the movables.txt file. However, most of the changes are only to replace TAKE with RAISE_UP and DROP with BEND_DOWN. But be aware that there are also some more changes (especially with the winegrower and the farmer).

**Comment by justangel** [comment]
BUILD SUCCESSFUL
Total time: 25 seconds

I have no problems at compile, strange ...

**Comment by andreas-eberle** [comment]
I restarted the tests and now they worked fine. 

Another thing: What do you think is the progress of this? How much work is still left to do for you?

**Comment by justangel** [comment]
to finish 11 file still have to go through 35 animations
If you need only the Romans, then I think that's it, but I'll check other files for Romans

**Comment by andreas-eberle** [comment]
At the moment we cannot support non-Roman peoples. Therefore it makes no sense to work on those yet.

**Comment by justangel** [comment]
Well, then, when I finish with the Romans, I told here

**Comment by justangel** [comment]
I experimented with revert commits =)

**Comment by justangel** [comment]
I ended up with Roman settlers

**Comment by andreas-eberle** [comment]
Hi Ivan,

Many thanks already! One thing: Pigs are not implemented as Movables but as map objects (see EMapObjectType). Can you remove them from the movables again?

Best regards

**Comment by justangel** [comment]
removed PIG from movables

**Comment by justangel** [comment]
lost tree resources by priority, immediately understood the reason
Not all droppable resources have a priority index

**Pull request merged**
