### PR TITLE
Move to gradle

### PR DESCRIPTION
**Pull request by michaelzangl**
This is almost ready to get merged.

## TODO
- @andreas-eberle re-structures the release zip a bit.
- Testing, Feedback
- (we might find more things).

## New directory layout
All projects use a new directory layout:
```
- src
  - main
    - java -> Java source files we need for the game
  - test
    - java -> Test files
```

All tests have access to all main source files, including the testutils subproject.

## Move to IntelliJ

Eclipse is no longer officially supported for Android.

With the change to gradle, the project structure changed and the new build scripts are not copatible to eclipse any more. Especially the tests won't build there that easilly.

You can use Eclipse or any other IDE but you might need to run gradle manually.

## Change all build scripts to gradle
- Ant scripts have been removed
- Eclipse projects are converted to a gradle subproject
- AndroidUI does not require any additional build steps any more.
-We use JGit to get the current revision. That way it should work on all platforms.
- Layout builder for graphics did not change. It was moved to a subproject to ease compilation. It is now in the code path for everyone to see and not some background magic.
- Tests are moved to the projects they belong to.
- A new testutils project contains classes that can be used by all tests.

## Build script commands

Some commands you can try:

```
./gradlew run
./gradlew runAndroid
./gradlew runMapCreator
./gradlew test
```

### CODE REVIEW

**Comment by andreas-eberle** [comment]
You moved the maps nicemap, settlerscraters and smallisland to the folder examples. What is the intention of this folder? Furthermore, a.map is only a testmap and should be in the test folder.

**Comment by michaelzangl** [comment]
I want to reduce the number of maps shipped with JSettlers - especially for Android

Those were the maps shipped by default. Feel free to move them.

We can have as much dictionaries as we want for development

**Comment by andreas-eberle** [comment]
I think we should ship those maps with JSettlers. They are playable and having only three maps shipped with the game is not a good idea.

**Comment by michaelzangl** [comment]
OK. But then remove or at least rename a.map ;-)

**Comment by michaelzangl** [comment]
Fixes  #282

**Comment by andreas-eberle** [comment]
The integration tests are never actually executed. Furthermoe, I would prefer to have the three main ITs seperated, as this makes it easier to see why a build failed and because they take a long time. If we separate them, Travis can parallelize them.

**Comment by andreas-eberle** [comment]
When I start the map editor in the UI, I'm not able to edit the existing maps.

**Comment by michaelzangl** [comment]
All maps should now show up in the editor.

**Comment by andreas-eberle** [comment]
When I try to start the MapEditor as application in IntelliJ (see screenshot for config), I get the following exception:

```
"C:\Program Files\Java\jdk1.8.0_77\bin\java" -Didea.launcher.port=7535 "-Didea.launcher.bin.path=D:\programs\IntelliJ IDEA\bin" -Dfile.encoding=UTF-8 -classpath "C:\Program Files\Java\jdk1.8.0_77\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\deploy.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\ext\zipfs.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\javaws.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\jfxswt.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\management-agent.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\plugin.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_77\jre\lib\rt.jar;D:\data\programming\java\programs\SettlersGradle\jsettlers.mapcreator\build\classes\main;D:\data\programming\java\programs\SettlersGradle\go.graphics\build\classes\main;D:\data\programming\java\programs\SettlersGradle\go.graphics.swing\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.common\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.graphics\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.graphics.swing\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.logic\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.network\build\classes\main;D:\data\programming\java\programs\SettlersGradle\jsettlers.main.swing\build\classes\main;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\edc35ccfc13d4a4ad02c50d580874c18bf48bbef\gluegen-rt-2.3.2.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\4c104c7aef98cda5c404eacb96b1a4e04fe0dd68\gluegen-rt-2.3.2-natives-android-aarch64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\2130295b94ef5c19f85fb4ba6107ca193e987858\gluegen-rt-2.3.2-natives-android-armv6.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\477a6bc4f9256d8c9935b75d55e2b7b01314440b\gluegen-rt-2.3.2-natives-linux-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\c55cd566d98d4fcd004b9aaa2c502c8c2dcec192\gluegen-rt-2.3.2-natives-linux-armv6.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\f6d3587b061d7ae6e68932fc62317e3500d2112d\gluegen-rt-2.3.2-natives-linux-armv6hf.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\da68aff010edd35a9ee89b1801dce6e284c7e673\gluegen-rt-2.3.2-natives-linux-i586.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\7227ae9e480354909d80f4df92b30bbb965387be\gluegen-rt-2.3.2-natives-macosx-universal.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\9a23cd22c59e3f04082e7589e850b79c9e696dc4\gluegen-rt-2.3.2-natives-solaris-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\a5d9ee96c7a365055fba41e30f9a10f42a3c1a3e\gluegen-rt-2.3.2-natives-solaris-i586.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\85213c97a5a50d8dd37de4c35ef32cd4b0ac2ef0\gluegen-rt-2.3.2-natives-windows-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.gluegen\gluegen-rt\2.3.2\f9b848384a343f39f454e59cead435c2c0cbf542\gluegen-rt-2.3.2-natives-windows-i586.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\99e0f64bb8882f054825ae4a8a527a17b544a0b5\jogl-all-2.3.2.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\166147f43cf7419c4d858cd31f4b5922d6d10c81\jogl-all-2.3.2-natives-android-aarch64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\ab2c18b8a1327255cc354c19c720807d262baa75\jogl-all-2.3.2-natives-android-armv6.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\ffd1c6bd5f6fb088df6cad25e25721eb55ad2228\jogl-all-2.3.2-natives-linux-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\6d14f46336be9e2dc5f85d5df17490cee5d09a90\jogl-all-2.3.2-natives-linux-armv6.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\2c434c560dbd821b0ed569e44d3d441727491dac\jogl-all-2.3.2-natives-linux-armv6hf.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\59b7a336c0ee54161e33662d2ca8ac9d8f6c476d\jogl-all-2.3.2-natives-linux-i586.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\2da2215dbe1091c54cb83cf2484f8a54a4d0cf7a\jogl-all-2.3.2-natives-macosx-universal.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\bde11ff064181af9c307180d8f3f1744b7bdc11d\jogl-all-2.3.2-natives-solaris-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\94d1ed501fe53b7f75eab0f712f39802390d0f5b\jogl-all-2.3.2-natives-solaris-i586.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\becd519b1f741176561d93645abd90971ca0dca0\jogl-all-2.3.2-natives-windows-amd64.jar;C:\Users\Andreas Eberle\.gradle\caches\modules-2\files-2.1\org.jogamp.jogl\jogl-all\2.3.2\5db8db5eca6b4445db6cd14f68938736630ae976\jogl-all-2.3.2-natives-windows-i586.jar;D:\programs\IntelliJ IDEA\lib\idea_rt.jar" com.intellij.rt.execution.application.AppMain jsettlers.mapcreator.main.MapCreatorApp --console-output
No default command line options file found.
Options loaded: {console-output=true}
Error launching application
java.lang.NullPointerException
	at java.util.Properties$LineReader.readLine(Properties.java:434)
	at java.util.Properties.load0(Properties.java:353)
	at java.util.Properties.load(Properties.java:341)
	at jsettlers.main.swing.resources.ConfigurationPropertiesFile.<init>(ConfigurationPropertiesFile.java:47)
	at jsettlers.main.swing.resources.ConfigurationPropertiesFile.<init>(ConfigurationPropertiesFile.java:40)
	at jsettlers.main.swing.resources.SwingResourceLoader.loadGamePathFromConfig(SwingResourceLoader.java:138)
	at jsettlers.main.swing.resources.SwingResourceLoader.setup(SwingResourceLoader.java:55)
	at jsettlers.main.swing.SwingManagedJSettlers.setupResourceManagers(SwingManagedJSettlers.java:110)
	at jsettlers.mapcreator.main.MapCreatorApp.main(MapCreatorApp.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Warning: Could not load LocaleSuffix [locale=en, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=de_DE, useCountry=false]. Falling back to next file.
Warning: Could not load LocaleSuffix [locale=de_DE, useCountry=true]. Falling back to next file.
```

unbenannt


When I run `gradlew runMapCreator`it works fine. Any ideas what is causing this?

**Comment by andreas-eberle** [comment]
@codingberlin: If I recall it correctly, you're an IntelliJ user, aren't you? Would you like to test this branch and give your feedback?

**Comment by codingberlin** [comment]
I'll test it.

**Comment by andreas-eberle** [comment]
@michaelzangl: Why is the distribution task not creating runnable jars as it was with ant?

**Comment by michaelzangl** [comment]
IntelliJ seems to have problems with the resources: The resources are recognized in the settings but when starting a java application, no resources are usable.

Somehow Android Studio seems to handle our projects better than IntelliJ. I'll have to see what they changed.

**Comment by codingberlin** [comment]
I was able to use IntelliJ IDEA with Gradle.
I wrote [Setting up (IntelliJ IDEA, OSX)](https://github.com/jsettlers/settlers-remake/wiki/Setting-up-%28eclipse%29) wiki page.

I was able to run the tests by Gradle out of IntelliJ IDEA GUI

**Pull request merged**
