### PR TITLE
fixes #218

### LINKED ISSUE #218: Computerplayer does not expand to stone fields before running out of stone
In general, the computerplayer does not expand towards stone fields enough. This can lead to a lack of stone that cannot be solved by the computerplayer any more. 

This can be reproduced on:
* mountainlake: The player in the lower left corner of the map fails to expand to the stone field at its start position.
* The new map Settlers Crater (as suggested in PR #217) causes both AI players to completely run out of stone, although their is stll a lot left. The AI would just need to expand there earlier.

### PR DESCRIPTION
**Pull request by codingberlin**
see #218

### CODE REVIEW

**Comment by andreas-eberle** [comment]
@codingberlin:
Regarding your last commit to touch the file: I think you should be able to log in on the Travis website to see all builds and be able to retrigger them manually.

**Comment by codingberlin** [comment]
I searched such a rebuild button but I was not able to find it. (When I'm logged in I cant find it, too)

**Comment by codingberlin** [comment]
See the update in #218. In my optioning this can be merges now.

**Comment by andreas-eberle** [comment]
@codingberlin: Sorry, I just wanted to update the branch and mixed in some other fixes I developed :( However, as I also wanted to have those fixes in the master, I will merge it, as soon as Travis is finished. Sorry for the mess....

**Comment by codingberlin** [comment]
@andreas-eberle no problem cause you cleaned it up ;)

**Pull request merged**
