### PR TITLE
replace nextDrawableX with x++

### PR DESCRIPTION
**Pull request by paulwedeck**

### CODE REVIEW

**Comment by andreas-eberle** [comment]
@michaelzangl: Why did you introduce this in the first place? I guess there was an idea to it?

**Comment by paulwedeck** [comment]
It has been introduced in bb15365a67b4a476391befa7e69de043c9fafac8

**Comment by michaelzangl** [comment]
It was meant to skip tiles of which we definitely know that there is noting to draw there.

This would have made rendering a bit faster.

**Comment by andreas-eberle** [comment]
"Nothing to draw" includes movables and objects?

**Comment by andreas-eberle** [comment]
@paulwedeck: Please only merge master into your Pull Request if there are conflicts with your PR. Otherwise, I can easily merge it with Github directly before I merge it into master. This way, we can prevent a ton of merge commits.

**Comment by michaelzangl** [comment]
@andreas-eberle Yes, no movables and no map objects.

**Comment by paulwedeck** [comment]
@andreas-eberle I will try

**Pull request merged**
