### PR TITLE
Android goods menus and mvvm refactoring

### PR DESCRIPTION
**Pull request by tom-pratt**
Added some more goods related menus. Then started refactoring many of the existing activities and fragments to use the Android Architecture Components.

Based on the ships branch so should be merged after that PR.

### CODE REVIEW

**Comment by andreas-eberle** [comment]
@tom-pratt: Can you update this branch to the current master? I think I'll soon get the ships branch into master, so we can then merge that in as well. I think since there are already so many conflicts, we should do two merges.

**Comment by andreas-eberle** [comment]
After I placed a building, the building counts disappeared in the menu.

**Comment by andreas-eberle** [comment]
When I go to the goods tab and switch around, then I go back to the buildings tab and back again to the goods tab, then I do not get back to the same tab in the goods tab. Instead, I always end up in the last subtab. Did you get what I mean?

**Comment by andreas-eberle** [comment]
What happend to the notification that was displayed when a game was running? On my Galaxy S8, there is no notification any more.

**Comment by andreas-eberle** [comment]
When you select the harbor, then select the button to choose the path target and place that target, the building menu does not pop up again. So I have to click the harbor again to get to the menu again.

**Comment by tom-pratt** [comment]
Oops didn't notice the comments till today. I'll take a look this weekend

**Comment by andreas-eberle** [comment]
@tom-pratt: I found a crash. Steps to reproduce:
* Start a new game and save it
* Exit the game
* Start the app again and load the savegame. When I do this fast, I get the following crash:

```
06-19 20:18:48.495 16828-16828/jsettlers.main.android E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: jsettlers.main.android, PID: 16828
                                                                        java.lang.RuntimeException: Unable to create service jsettlers.main.android.core.GameService_: java.lang.NullPointerException: Attempt to invoke virtual method 'android.arch.lifecycle.LiveData jsettlers.main.android.core.controls.GameMenu.getGameState()' on a null object reference
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3552)
                                                                            at android.app.ActivityThread.-wrap4(Unknown Source:0)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                            at android.os.Looper.loop(Looper.java:164)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6938)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
                                                                         Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.arch.lifecycle.LiveData jsettlers.main.android.core.controls.GameMenu.getGameState()' on a null object reference
                                                                            at jsettlers.main.android.core.GameService.createNotification(GameService.java:108)
                                                                            at jsettlers.main.android.core.GameService.onCreate(GameService.java:71)
                                                                            at android.app.ActivityThread.handleCreateService(ActivityThread.java:3542)
                                                                            at android.app.ActivityThread.-wrap4(Unknown Source:0) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1786) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                                            at android.os.Looper.loop(Looper.java:164) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6938) 
                                                                            at java.lang.reflect.Method.invoke(Native Method) 
                                                                            at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
06-19 20:18:49.288 16828-16833/jsettlers.main.android I/zygote64: Do partial code cache collection, code=30KB, data=18KB
06-19 20:18:49.288 16828-16833/jsettlers.main.android I/zygote64: After code cache collection, code=27KB, data=17KB
06-19 20:18:49.288 16828-16833/jsettlers.main.android I/zygote64: Increasing code cache capacity to 128KB
```

**Comment by tom-pratt** [comment]
I think this crash is a side effect of a crash in the audio player. I see that the app crashes with this audio exception. Then it restarts due to starting the GameService but this crashes immediately because the current state has been lost due to the previous crash.

```06-22 20:32:53.909 1634-2418/? E/AudioTrack: AudioFlinger could not create track, status: -12
06-22 20:32:53.913 1634-2416/? E/AudioTrack-JNI: Error -12 initializing AudioTrack
06-22 20:32:53.913 1634-2416/? E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
06-22 20:32:53.913 1634-2416/? W/AudioTrack: Use of stream types is deprecated for operations other than volume control
06-22 20:32:53.914 1634-2416/? W/AudioTrack: See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-22 20:32:53.915 1634-2416/? E/AndroidRuntime: FATAL EXCEPTION: soundplayer3
    Process: jsettlers.main.android, PID: 1634
    java.lang.IllegalStateException: play() called on uninitialized AudioTrack.
        at android.media.AudioTrack.play(AudioTrack.java:1979)
        at go.graphics.android.AndroidSoundPlayer$PlaySoundTask.run(AndroidSoundPlayer.java:61)
        at java.lang.Thread.run(Thread.java:764)
06-22 20:32:53.933 1634-2415/? E/AudioTrack-JNI: Error -12 initializing AudioTrack
06-22 20:32:53.934 1634-2415/? E/android.media.AudioTrack: Error code -20 when initializing AudioTrack.
06-22 20:32:53.934 1634-2415/? W/AudioTrack: Use of stream types is deprecated for operations other than volume control
    See the documentation of AudioTrack() for what to use instead with android.media.AudioAttributes to qualify your playback use case
06-22 20:32:53.934 1634-2415/? I/Process: Sending signal. PID: 1634 SIG: 9```

**Comment by tom-pratt** [comment]
I think this crash was probably there before this PR. I think we should merge and fix it separately

**Pull request merged**
