### PR TITLE
Added some more maps to the release folder. 

### PR DESCRIPTION
**Pull request by andreas-eberle**

### CODE REVIEW

**Comment by andreas-eberle** [comment]
@codingberlin: What do you think about the three maps (apart from SpezialSumpf)?

**Comment by michaelzangl** [comment]
I think we should use a better naming scheme for the file names.

**Comment by andreas-eberle** [comment]
Well, the filenames are not really of interest for the user. He will see a better name in the UI. For now I oriented the filenames on the ones used in the original game (map size-max players-map name). Once the UI displays the map's properties better, we can get rid of the map size-max players prefix. For now, I think it is ok.

@codingberlin: What do you think?

**Comment by michaelzangl** [comment]
But the file name is what we devs use to find out which map is which. I would like to have the same naming scheme for all files in that directory.

**Comment by andreas-eberle** [comment]
@michaelzangl: I changed the naming scheme of the remake maps to 
`<mapsize>-<max playable players>-<name_with_underlines>.<ending>`

I did not change the naming of SpecialSumpf_20, as this is a map downloaded from the settlers mapbase maps designed for the original game by @codingberlin. What do you think?

**Comment by codingberlin** [comment]
The  schema of the map name is not so important for me cause of the search in the GUI.

**Comment by michaelzangl** [comment]
Names are much better now ;-)

**Pull request merged**
