### PR TITLE
Map Settler Craters

### PR DESCRIPTION
**Pull request by abledbody**
A little map I made consisting of 3 interconnected craters, surrounded by impassible snowy mountains.

Also an excellent demonstration of #215.

### CODE REVIEW

**Comment by andreas-eberle** [comment]
Many thanks for building this map. It's great to have new maps for the players and for testing.

However, I think the current version has very small amounts of stone per player. Is this intended? Maybe we should increase the amount of stone.

**Comment by abledbody** [comment]
@andreas-eberle I've been able to play the map without running out of stone, I don't think most players will before filling up their crater with buildings. I can up the stone count a bit if you think it needs it, but I think it might cramp the player in a little.

**Comment by codingberlin** [comment]
Hey very good work!
This map helped to figure out some issues with the computerplayer.

(It would be wonderfully, if you add some small sea with fish for the goldmines.)

**Comment by codingberlin** [comment]
By the way: I am such a player which fills the crater and runs out of stone by building a lot of living houses to produce mass of soldiers.

**Comment by abledbody** [comment]
Oh, by the way, @codingberlin, Residences are only to keep Carriers happy, if you make a large residence and then make 50 soldiers you can destroy it to save some space.

**Comment by codingberlin** [comment]
That's true, but you only get half of the material back thus you run out off stone sometime. But maybe low stone amout is one key point of the map which forces you to rush or attack in the midgame if you want to win.

However I think your map rocks:)

**Comment by abledbody** [comment]
Just in case you guys missed it, I updated the map.

**Comment by codingberlin** [comment]
+1

I tested the map again. From my perspective, it can be merged now.

**Comment by abledbody** [comment]
@codingberlin Sweet.

**Comment by andreas-eberle** [comment]
@abledbody: Thanks for the map!

**Pull request merged**
