### PR TITLE
show shadows

### PR DESCRIPTION
**Pull request by rpolzer**

### CODE REVIEW

**Comment by andreas-eberle** [comment]
At first: Very cool! Thanks a lot already!

One thing I saw is that some shadows do not match the objects for which they are drawn. E.g.

grafik

Can you fix this @rpolzer?

**Comment by tomsoftware** [comment]
for your information, the mapping between shadow / body / object image is in the e.g. "siedler3_15.7c003e01f.dat" file. The format of this file is:
https://github.com/tomsoftware/sied3/blob/master/src/clGFXFile.cpp#L218
and
https://github.com/tomsoftware/sied3/blob/master/src/clGFXFile.cpp#L263

I would like to help here but don't have mutch time at the moment. May the first step is to use the "siedler3_15" file to create the "remake index list"?

**Comment by andreas-eberle** [comment]
@rpolzer: How are the shadows mapped at the moment? 

@tomsoftware: Thanks for these hints. It would be great to be able to integrate this.

**Comment by rpolzer** [comment]
At the moment I am on the road - I will try to give answers within three days.

**Comment by rpolzer** [comment]
The torso drawing remains unchanged. The shadows are drawn the same way as the torsos, and the shadow information comes from the same GFX file. Torsos are encoded with sequenceType == ID_TORSOS and shadows are encoded with sequenceType == ID_SHADOWS.

The new function shadow.drawAt() works nearly identical to the function torso.drawAt(), they both use the AdvancedDatFileReader function DatBitmapReader.getImage(), one with the new shadowTranslator and the other with the existing torsoTranslator.

The shadowTranslator returns an alpha value A = 0 or A = 0.5 in color coding 4444. And the whole graphics had to be changed from color coding 5551 to 4444 to enable shadows of different darkness - when using color coding 5551 as before, A may be only zero or one.

I know that some things have a wrong shadow, as for example the poles of a building site. I will try to correct that with one of the next commits. This is due to the fact that the GFX files sometimes contain less shadow images than settler images.

**Comment by andreas-eberle** [comment]
I just had a look and found some more things:

* The water looks a bit strange:
grafik

* In the menu where I can select the map to load, the preview maps look very strange. The colors where different before. 
grafik

* The flags on buildings look strange:
grafik

* Some buildings have no shadows (e.g. lumberjack and sawmill)


I guess, we should take a look at the code proposed by @tomsoftware to be able to always load the correct shadows without having to manually specify them. This would also ensure that the shadows work when different versions of the game are used. @rpolzer: Can you have a look at the code of @tomsoftware?

**Comment by rpolzer** [comment]
@tomsoftware: your gfx file reader declares 8 sequence types (GFX_Type____COUNT), but the gfx file reader used here reads only 6 sequence types (SEQUENCE_TYPE_COUNT). As soon as I try to increase this number to 8, I do not get reasonable sequences. So I can not read the sequence you use for getting the animation info (containing torso id, shadow id etc.) for each of the objects.

If we could resolve this, the manual correlation of shadows to objects could be made automatically.

@andreas-eberle: the ugly map preview colors are due to the fact that I had to change from color coding 5551 to 4444. This has not yet be done for map previews.

The missing house shadows and the wrong house flag seem to be the same problem as above - body and shadow index do not match and either must be corrected manually - or we get a solution for an automatic index matching.

**Comment by krullgor** [comment]
@rpolzer i implemented parsing the animation mappings: https://github.com/krullgor/settlers-remake/commit/fee3b0de2111bb26255f073125241544639c5230 but its only for movables, shadow mapping for buildings is still missing.. @tomsoftware do you know where building mappings are stored?

**Comment by rpolzer** [comment]
@krullgor: I tried the branch you mentioned, and tested the reading of the animation info sequence. I am using the gold edition settler III files, and there the length of the animation info is zero for all gfx dat files. So I think we cannot use any automated index matching for shadows.

**Comment by krullgor** [comment]
@rpolzer all animation info for romans is in 15, in this other roman gfx files are referenced

**Comment by rpolzer** [comment]
This will take some time

**Comment by rpolzer** [comment]
I found animation info

for romans in file 15
for egyptins in file 25
for asians in file 35
for amazones in file 45

- but this is only for people. I found no info for houses and other stuff.

So this is no solution for the remaining shadow problems.

**Comment by andreas-eberle** [comment]
@rpolzer: I'm currently implementing an automated mapping for the indexes of graphics in the different game versions. I think this could fix these problems and we would be able to simply stick to the hard coded image indexes of the gold version. I'll try it to see if it works.

What original settlers version do you have @rpolzer?

**Comment by rpolzer** [comment]
Die Siedler III Gold Edition (German)

**Comment by andreas-eberle** [comment]
@rpolzer: Thanks already for all this work!

I merged the automated mapping of graphics files for the none-Gold versions of the game. So we can simply hard code the gold version indexes. With the current implementation, I found the following bugs. Can you have a look at them?

- [ ] When selecting a building to build, the overlayed building has a flickering part switching between the building's image and the background
grafik
- [ ] The flags on buildings have a background
grafik
- [ ] The poles used to display the work are have strange shadows in the innermost circle and no shadows on the other circles. I think it would be best to not let them have shadows at all, as it is a "ui element".
grafik
- [ ] When a building is selected, the selection mark's background seems to put the building's image part on top of people and materials standing in front of the building. I guess the transparent parts of the selection mark change the values in the depth buffer or something like that. The same happens to a person standing next to a wood pile.
grafik
grafik

So much for now. If I find some more, I'll add them here.

**Comment by rpolzer** [comment]
- this commit solved building flag, building selection mark and pile corner errors

**Comment by rpolzer** [comment]
I just searched how to improve the flickering when placing a new building:
This flickering is gone when changing the alpha level from 0.5 to 0.55 for not writing the z buffer:

in file JOGLDrawContext.java, line 209
    gl2.glAlphaFunc(GL.GL_GREATER, 0.55f) ; // prevent writing of transparent pixels to z buffer

But then the strokes of the text in the UI begin to fade out, for example the building names. I could need a hint where this text appearence is defined.

**Comment by andreas-eberle** [comment]
@michaelzangl: Can you help @rpolzer with his question?

**Comment by michaelzangl** [comment]
Yes, this really is a problem with the Z-Drawing. You should only set the Z index if the given pixel is solid.

The old way of fixing this is:
```
glAlphaFunc(GL_GREATER, 0.1);
glEnable(GL_ALPHA_TEST);
```

This will prevent the depth buffer from being updated for transparent pixels.

You can achive this using a shader as well.

Can you post a picture of the problem with the fonts?

**Comment by rpolzer** [comment]
setting the alpha limit to 0.5:


setting the alpha limit to 0.55:

**Comment by rpolzer** [comment]
setting the alpha limit to 0.55 is no solution, because the shadows are gone - I don't know why I did not see that...

**Comment by rpolzer** [comment]
now I think all mentioned shadow errors are resolved, including flicker of building placement, but there might be a better way to do that...

**Comment by andreas-eberle** [comment]
@michaelzangl: Can you have a look if you see a better way, or if it is ok like this? Thx.

**Comment by andreas-eberle** [comment]
@rpolzer: Thanks for fixing all these things! However, I have one more thing: Some buildings seem to not have shadows (e.g. the lumberjack and the small and large living house). Are the shadow indexes manually specified? If, so, where can I find the mapping?

grafik

**Comment by rpolzer** [comment]
The shadows for the buildings are used with the same indexing as in the file.

**Comment by rpolzer** [comment]
Now I shifted all building shadow indexes - all buildings now seem to have the right shadow.
One thing remaining to do is the windmill: animation of the windmill produces a big switching shadow.

**Comment by rpolzer** [comment]
I found a better way to draw non flickering building placement and resolved the windmill problem.

**Comment by andreas-eberle** [comment]
For many buildings the shadows now look fine. However, for the following buildings, the shadows still seem to be wrong:
- [ ] charcoal burner 
- [ ] donkey farm 
- [ ] wine grower
- [ ] dock 
- [ ] hospital 
- [ ] barracks 
- [ ] large temple
- [ ] small temple
- [ ] market
- [ ] harbor

Also, when I started the game, I saw the following error in the console log 
```
Main draw handler cought throwable:
java.lang.ArrayIndexOutOfBoundsException: 66
	at jsettlers.graphics.image.reader.AdvancedDatFileReader.initialize(AdvancedDatFileReader.java:346)
	at jsettlers.graphics.image.reader.AdvancedDatFileReader.initializeIfNeeded(AdvancedDatFileReader.java:458)
	at jsettlers.graphics.image.reader.AdvancedDatFileReader.access$300(AdvancedDatFileReader.java:116)
	at jsettlers.graphics.image.reader.AdvancedDatFileReader$DirectSettlerSequenceList.size(AdvancedDatFileReader.java:486)
	at jsettlers.graphics.map.draw.ImageProvider.getSettlerSequence(ImageProvider.java:259)
	at jsettlers.graphics.map.draw.MapObjectDrawer.drawPlayerBorderObject(MapObjectDrawer.java:856)
	at jsettlers.graphics.map.MapContent.drawTile(MapContent.java:526)
	at jsettlers.graphics.map.MapContent.drawMain(MapContent.java:485)
	at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:286)
	at go.graphics.region.Region.drawRegion(Region.java:103)
	at go.graphics.area.Area.drawRegionAt(Area.java:132)
	at go.graphics.area.Area.drawArea(Area.java:120)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:165)
	at go.graphics.swing.AreaContainer$1.display(AreaContainer.java:97)
	at jogamp.opengl.GLDrawableHelper.displayImpl(GLDrawableHelper.java:692)
	at jogamp.opengl.GLDrawableHelper.display(GLDrawableHelper.java:674)
	at com.jogamp.opengl.awt.GLCanvas$11.run(GLCanvas.java:1424)
	at jogamp.opengl.GLDrawableHelper.invokeGLImpl(GLDrawableHelper.java:1293)
	at jogamp.opengl.GLDrawableHelper.invokeGL(GLDrawableHelper.java:1147)
	at com.jogamp.opengl.awt.GLCanvas$12.run(GLCanvas.java:1438)
	at com.jogamp.opengl.Threading.invoke(Threading.java:223)
	at com.jogamp.opengl.awt.GLCanvas.display(GLCanvas.java:505)
	at com.jogamp.opengl.awt.GLCanvas.paint(GLCanvas.java:559)
	at sun.awt.RepaintArea.paintComponent(RepaintArea.java:264)
	at sun.awt.RepaintArea.paint(RepaintArea.java:240)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by rpolzer** [comment]
Now all building shadows seem to be ok

**Comment by andreas-eberle** [comment]
The soldier in the tower looks a bit dark. Is don't think that is correct. It looks like a dark shadow is over the person.

grafik

**Comment by rpolzer** [comment]
still missing shadows:
- donkey
- donkey farmer when fetching wheat

**Comment by rpolzer** [comment]
now all mentioned errors should be solved

**Comment by andreas-eberle** [comment]
I think the material stacks might have some errors. E.g.

grafik

grafik

Most material stack don't seem to have shadows yet. 

@rpolzer: Sorry for finding yet another thing and thanks for all your work!

**Comment by andreas-eberle** [comment]
@rpolzer: Can you resolve the merge conflict?

**Comment by rpolzer** [comment]
I will do some more checking

**Comment by rpolzer** [comment]
looks OK now, on PC and Android

**Comment by andreas-eberle** [comment]
@rpolzer: Thanks a lot for this big change!

**Pull request merged**
