### PR TITLE
fixed farmer cut animation

### PR DESCRIPTION
**Pull request by justangel**

### CODE REVIEW

**Comment by justangel** [comment]
compilation error? I have something somewhere forgot?
I have a farmer now correctly animates

**Comment by andreas-eberle** [comment]
Hi @justangel,

no, you didn't forget anything. However, as you changed the job names and these are saved within the savegame, the AutoReplayIT fails. 

In cases like this, you should check that it really works and breaks nothing else (this time it's a simple change and I guess you already checked it). After that, you can run AutoReplayIT once to see which reference files are failing. In your case not all should fail as there is at least one test with fighting only => no farmer on the map => no change should have happend. If that is the case, run the main method of the AutoReplayIT class to regenerate the reference files and commit them.

best regards

**Comment by justangel** [comment]
hi, i tested and it works like it should

**Comment by justangel** [comment]
for the first time generated normally
after that continue keeping error

New replay file successfully created!
Replayed: resources\autoreplay\fullProduction-mountainlake\replay.log and created savegame: G:\JSettlers\jsettlers.tests\..\jsettlers.main.swing\..\jsettlers.common\resources\save\mountainlake-2015-09-30_21-03-30.zmap
Comparing expected 'resources\autoreplay\fullProduction-mountainlake\savegame-30m.map' with actual 'G:\JSettlers\jsettlers.tests\..\jsettlers.main.swing\..\jsettlers.common\resources\save\mountainlake-2015-09-30_21-03-30.zmap' (uncompressed!)
Exception in thread "main" java.io.IOException: Map header start is invalid.
	at jsettlers.logic.map.save.MapFileHeader.readFromStream(MapFileHeader.java:179)
	at jsettlers.tests.autoreplay.AutoReplayIT.compareMapFiles(AutoReplayIT.java:117)
	at jsettlers.tests.autoreplay.AutoReplayIT.main(AutoReplayIT.java:174)

**Comment by justangel** [comment]
new error "Map header start is invalid" when try to compile

**Comment by andreas-eberle** [comment]
Please try deleting the reference file that makes you problemes. This should help. In your example it would be `resources\autoreplay\fullProduction-mountainlake\savegame-30m.map`

**Comment by justangel** [comment]
i delete savegame-30m.map
error in savegame-40m.map
i delete savegame-40m.map
error in savegame-69m.map
all is ok and created files have zmap extension

**Pull request merged**
