### PR TITLE
LWJGL support

### PR DESCRIPTION
**Pull request by paulwedeck**
Why should you drop the lwjgl branch and merge this patch ? This patch is actually working (lwjgl branch does not work on my computer), is much smaller (~600 vs ~1400 new lines) and integrates into swing windows.

What does not work correctly ? font drawing isnt good but working.
Edit: "GLX windows cant be enlarged (causes black border)" has been fixed

Notes:
- Async backend syncs between glReadPixels and JPanel#paint. This is a large performance decrease (20fps vs 200fps but does not affect game)
- GLX backend does not affect performance

Edit: "- WGL backend was not tested" removed
Edit: "there is a workaround for the async/glfw problem: press m and play in the glfw "offscreen" window

### CODE REVIEW

**Comment by andreas-eberle** [comment]
How exactly can I start the game so it uses your new LWGL renderer? I have a Windows10, so I could test it on this OS. Also, can you continue working on it to fix the remaining issues you pointed out? If we get this to the level of the JOGL rendering, I would be very happy to take it instead of the JOGL rendering.

**Comment by paulwedeck** [comment]
simply call `gradlew run` to run it.
Some problems are concept dependent like the glfw/async problem but I will look at the glx one.

**Comment by andreas-eberle** [comment]
Is there something we can do about the glfw/async problem? Or what exactly is causing this problem?

**Comment by paulwedeck** [comment]
I just did a few testing with removing code and look at the fps.
Removing the whole synchronized block at AsyncContextCreator(line 117) gives around 1000 fps.
Only doing glReadPixels reduces this to 200fps, so speeding up/replacing bi.setRGB would be a good performance increase (my latest "measurements" gives around 25 fps with BufferedImage).

I have never worked with glReadPixels before and the internet says it is very slow, so I expected such a poor performance but obviously I underestimated the overhead of BufferedImage.

**Comment by andreas-eberle** [comment]
Unfortunately, I get the following error:

```
[LWJGL] Version: 3.1.5 build 1
[LWJGL] 	 OS: Windows 10 v10.0
[LWJGL] 	JRE: 1.8.0_151 amd64
[LWJGL] 	JVM: Java HotSpot(TM) 64-Bit Server VM v25.151-b12 by Oracle Corporation
[LWJGL] Loading library (system): lwjgl
[LWJGL] 	Found at: C:\Users\ANDREA~2\AppData\Local\Temp\lwjglAndreas Eberle\3.1.5-build-1\lwjgl.dll
[LWJGL] 	Loaded from org.lwjgl.librarypath: C:\Users\ANDREA~2\AppData\Local\Temp\lwjglAndreas Eberle\3.1.5-build-1\lwjgl.dll
[LWJGL] MemoryUtil accessor: MemoryAccessorUnsafe
[LWJGL] Loading library: jawt
[LWJGL] 	jawt.dll not found in org.lwjgl.librarypath=C:\Users\ANDREA~2\AppData\Local\Temp\lwjglAndreas Eberle\3.1.5-build-1
[LWJGL] 	jawt.dll not found in system paths
[LWJGL] 	jawt.dll not found in java.library.path=C:\Program Files\Java\jdk1.8.0_151\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;;D:\programs\python3.5\;D:\programs\python3.5\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\PuTTY\;C:\Program Files\Git\cmd;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\ProgramData\chocolatey\bin;C:\Program Files\Java\jdk1.8.0_151\bin;c:\tools\msys64\usr\bin;D:\programs\Matlab\bin;C:\Program Files (x86)\protoc\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Andreas Eberle\AppData\Local\Programs\Python\Launcher\;D:\programs\python3.5\Scripts\;D:\programs\python3.5\;C:\Users\Andreas Eberle\AppData\Local\Microsoft\WindowsApps;C:\Program Files\apache-maven-3.3.9\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\msys2;C:\tools\msys64;D:\programs\apache-ant-1.10.0/bin;D:\Android\SDK\platform-tools;D:\programs\swigwin-3.0.12;C:\Program Files\NVIDIA Corporation\NVSMI;D:\programs\MiKTex\miktex\bin\x64\;.
[LWJGL] Failed to load a library. Possible solutions:
	a) Install the library or the driver that provides the library.
	b) Ensure that the library is accessible from the system library paths.
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: Failed to locate library: jawt.dll
	at org.lwjgl.system.Library.loadNative(Library.java:289)
	at org.lwjgl.system.Library.loadNative(Library.java:186)
	at org.lwjgl.system.jawt.JAWTFunctions.<clinit>(JAWTFunctions.java:68)
	at go.graphics.swing.contextcreator.JAWTContextCreator.<init>(JAWTContextCreator.java:38)
	at go.graphics.swing.contextcreator.WGLContextCreator.<init>(WGLContextCreator.java:33)
	at go.graphics.swing.AreaContainer.<init>(AreaContainer.java:71)
	at jsettlers.main.swing.JSettlersFrame.lambda$setContent$1(JSettlersFrame.java:166)
	at jsettlers.main.swing.JSettlersFrame$$Lambda$2.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I tried to find which native library needs to be added, but wasn't successful. Do you have an idea? I guess an additional import has to be added to gradle, am I right?

**Comment by paulwedeck** [comment]
No, you jdk should provide this library.
Your java is slightly older than mine(1.8.0_161>1.8.0_151), have you tried to update it ?

**Comment by andreas-eberle** [comment]
I just updated to 1.8.0_162 but it didn't help...

**Comment by paulwedeck** [comment]
Is it still the same error ?

I have downloaded the 1.8.0_162 and 1.8.0_161 windows versions from oracle.
Both of them contain jawt.dll in their bin dir.

**Comment by andreas-eberle** [comment]
OK, I found the problem: The JDK does not contain the jawt.dll in its bin directory but in the jre folder. It finds the lib when I run it with a JRE. The screen is now rendered. However, I get flooded with the following exception: 
```
Main draw handler cought throwable:
java.lang.NullPointerException
	at go.graphics.swing.opengl.LWJGLDrawContext.startWriteGeometry(LWJGLDrawContext.java:450)
	at jsettlers.graphics.map.draw.Background.drawMapContent(Background.java:1195)
	at jsettlers.graphics.map.MapContent.drawBackground(MapContent.java:572)
	at jsettlers.graphics.map.MapContent.drawContent(MapContent.java:283)
	at go.graphics.region.Region.drawRegion(Region.java:103)
	at go.graphics.area.Area.drawRegionAt(Area.java:132)
	at go.graphics.area.Area.drawArea(Area.java:120)
	at go.graphics.swing.AreaContainer.draw(AreaContainer.java:114)
	at go.graphics.swing.contextcreator.JAWTContextCreator$1.paint(JAWTContextCreator.java:82)
	at go.graphics.swing.contextcreator.JAWTContextCreator$1.update(JAWTContextCreator.java:50)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
	at sun.awt.windows.WComponentPeer.handleEvent(WComponentPeer.java:358)
	at java.awt.Component.dispatchEventImpl(Component.java:4965)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by paulwedeck** [comment]
It seams that wgl context creations has failed.

Putting this after line 62 in WGLContextCreator.java might help:
`
pfd.nSize((short) PIXELFORMATDESCRIPTOR.SIZEOF);
pfd.nVersion((short) 1);
`

**Comment by andreas-eberle** [comment]
No luck, it did not help :(
A side node: Please use tab for indentation.

**Comment by paulwedeck** [comment]
Maybe this line helps:
`pfd.iPixelType(GDI32.PFD_MAIN_PLANE);`

Im using tabs for indentation but in some files android studio has replaced them with spaces (as example LWJGLDrawContext uses tabs).

**Comment by andreas-eberle** [comment]
Unfortunately this did not help either :( 
Can you join our Discord channel? Then we can discuss it more directly. https://discord.gg/2hVV4u6

Regarding indentation: OK, then we will reformat these files in the end before we merge this to get all with tabs.

**Comment by paulwedeck** [comment]
Have you used all three lines together ? I tried them under wine and it worked.

I have joined your discord server, my name there is paul.

**Comment by andreas-eberle** [comment]
I've pushed a minimalistic fix for the Windows crashes. It now works on my Windows 10 laptop. @paulwedeck: Thanks for all the debugging help!

**Comment by andreas-eberle** [comment]
Some things regarding the settings:

* When I select the glfw option in the settings menu, a second window opens and I get only about 2-3 fps. Is this the same for you? If you, I don't think we need that option...

* When I select glx I get the following error. I guess we should not show this option on windows if it only works for Linux.
```
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class org.lwjgl.system.linux.X11
	at go.graphics.swing.contextcreator.GLXContextCreator.initContext(GLXContextCreator.java:51)
	at go.graphics.swing.contextcreator.JAWTContextCreator$1.paint(JAWTContextCreator.java:63)
	at go.graphics.swing.contextcreator.JAWTContextCreator$1.update(JAWTContextCreator.java:50)
	at sun.awt.RepaintArea.updateComponent(RepaintArea.java:255)
	at sun.awt.RepaintArea.paint(RepaintArea.java:232)
````

**Comment by paulwedeck** [comment]
No I get 20fps with glfw.
GLFW is our only osx implementation, so I wouldn`t drop it and there is much space for improvements.

GL**X** is a **X** thing, so its not limited to linux.
There are indeed Windows(http://x.cygwin.com/) and OSX (https://www.xquartz.org/) implementations for it. 
I would rather check for X and disable the GLX option or print an error dialog.

We could also implement a native osx (NSGL) backend but I cant find any documentation about.

**Comment by andreas-eberle** [comment]
ok, am I right then, that we now "only" need to test this to see if it works on all platforms?

**Comment by paulwedeck** [comment]
There is a bug with changing from/to fullscreen and the glfw offscreen window does not support fullscreen at all.
Async (GLFW) has still a poor performance but none of these is critical or easy to fix,so yes if we can be sure that everything works on every platform we can merge it.

**Comment by andreas-eberle** [comment]
@paulwedeck: Can you merge master to fix the merge conflict?

**Comment by andreas-eberle** [comment]
@paulwedeck: Thanks for your work!

**Pull request merged**
