### PR TITLE
Enabled responsive image resolution for building panel images.

### PR DESCRIPTION
**Pull request by adamjryan**
The building images now use higher resolution versions when there
are enough pixels available for the image to be drawn in (larger
screen size).
This also applies for other icons in the control panel.

### CODE REVIEW

**Comment by adamjryan** [comment]
That doesn't appear to be related to anything I've changed - temperamental network tests?

**Comment by andreas-eberle** [comment]
Yes, the tests have some issues, which I'm working on. I restarted your builds.

**Comment by adamjryan** [comment]
Thanks, Travis is happy again.

**Comment by michaelzangl** [comment]
Thanks for the patch.
Can you please use the formatter settings we provided (see README), so that there are no code format conflicts. I also made some modifications of your code, mainly to remove duplications.

**Pull request merged**
