### PR TITLE
Feature influence weaponproduction

### PR DESCRIPTION
**Pull request by codingberlin**
See #210

What you can do now:
- Set up to 20 Bow/Sword/Spear productions
- Set ratio of Bow/Sword/Spear with blue bars

The weapon smiths will produce what you defined in the given ratio.
If you add 10 bows and 20 swords, bows and swords will be produces in 1:2 ratio until the prios were produces.

If you click on the tools prio buttons or bars, nothing happens.

The WinnerGeneral will produce some swords to occupy towers, 20 spears to defeat rushs and then only bows.

### CODE REVIEW

**Comment by codingberlin** [comment]
Ich schau mir die kommenden Tage an, warum das buildSwing Target nicht mehr geht.

**Comment by codingberlin** [comment]
(Sorry for writing the last comment in German. I even didn't notice that I did it :P)

The builds are green now so for my perspective this can be merged.

**Comment by andreas-eberle** [comment]
@codingberlin: There seems to be a bug in the UI here. The tool tip message of the weapon production bars should display the percentage of swords, bows and spears that should be produced by the weapon smiths. At the moment, it only displays the percentage of how much the ui bar is filled.

**Comment by codingberlin** [comment]
@andreas-eberle I fixed that now.
e.g. if you fill the bars swords 100% and bows 100% the bar descriptions show 50% now.

**Pull request merged**
