### PR TITLE
Maps and saves updated upon load of main menu.

### PR DESCRIPTION
**Pull request by adamjryan**

### CODE REVIEW

**Comment by andreas-eberle** [comment]
Am I right that this is a fix for #108?

**Comment by adamjryan** [comment]
Yep, it might fix the issue on Android also.

**Comment by andreas-eberle** [comment]
@adamjryan: I integrated some of your changes/ideas in my larger PR #132. I found it necessary to refactor the whole system a bit before integrating your changes/fixing the bug.

**Comment by adamjryan** [comment]
Glad it was of use, cheers.

**Pull request merged**
