### PR TITLE
New Settler 3 folder selection dialog (Startup of the Game)

### PR DESCRIPTION
**Pull request by andreasb242**
bildschirmfoto vom 2016-01-23 16 32 07

Tree folder selection, valid Settler folders are highlighted with a red arrow.
Help Button opens an URL, which points currently to wiki, I currently don't know where I should link it, but I would prefer a separate How-To (because I read the DEMO installation also works).

### CODE REVIEW

**Comment by andreasb242** [comment]
>  [junit] Testcase: jsettlers.tests.replay.AutoReplayIT:testReplay[4: fullProduction-mountainlake : 40]: Caused an ERROR
>
>    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
>
>    [junit] Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.
>
>    [junit] junit.framework.AssertionFailedError: Forked Java VM exited abnormally. Please note the time in the report does not reflect the time until the VM exit.

@andreas-eberle Do you know this error?
I only merged master...

**Comment by andreas-eberle** [comment]
I don't know the error. But I will have a look. I just restarted the build to test if it was a temporary Travis issue...

**Comment by andreas-eberle** [comment]
I was finally able to find time... after some trial and error, I figured out, that the junit ant task just ran out of memory... unfortunately it isn't telling that and works on my machine. However, after increasing the heap size of the failing tasks (see 30f8c2e6a611fcd3112b1e44580d1c80a19967da), it worked.

Is started a new Pull Request #306, as I cannot edit this one. => I will close this one.

**Comment by andreasb242** [comment]
Thank you ;-)

**Pull request closed without merging**
